Proj 1 vector operations
Anton-Rampage/made-cpp-2020-hw pull request #2
Opened 2020-09-26 10:12 UTC by Anton-Rampage

Я реализовал все операции и для int и для double(не знаю нужно ли это было) ну кроме `|` и `&`, сделал с помощью шаблонов и концептов

2020-10-15 20:32 UTC, xterrafunny requested changes

2020-10-15 20:32 UTC, xterrafunny commented on vector_operations/src/vector_ops.h
> +    std::vector<T> res_vector;
Отступ 2 пробела

2020-10-15 20:32 UTC, xterrafunny commented on vector_operations/src/vector_ops.h
> +std::vector<T> operator+(const std::vector<T> &first, const std::vector<T> &second) {
Длина строки не больше 80 символов

2020-10-15 20:32 UTC, xterrafunny commented on vector_operations/src/vector_ops.h
> +    }
Проверки при делении на ноль

2020-10-15 20:32 UTC, xterrafunny commented on vector_operations/src/vector_ops.h
> +    for (size_t i = 0, j = vec.size() - 1; i < vec.size(); ++i, ++j) {
Получше посмотри на эту строку

2020-11-03 03:22 UTC, SweetWeakness commented
принимаем, но из-за конфликтов не вмердживаем

2020-11-03 03:22 UTC, closed without merging